### ISSUE TITLE
复制dll后，在houdini里搜不到TwinTex

### ISSUE THREAD

**Issue by nangongliufeng** [Ligo04/TwinTex#3]
我编译了houdini自带的源码，能搜到，但是twintex搜不到
![图片](https://github.com/Ligo04/TwinTex/assets/87115602/7df0aeb5-919c-4e1c-9396-5138e6967b7a)

**Comment by Ligo04** [comment]
> 我编译了houdini自带的源码，能搜到，但是twintex搜不到 ![图片](https://private-user-images.githubusercontent.com/87115602/290063089-7df0aeb5-919c-4e1c-9396-5138e6967b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjM2MDcsIm5iZiI6MTcwMjUyMzMwNywicGF0aCI6Ii84NzExNTYwMi8yOTAwNjMwODktN2RmMGFlYjUtOTE5Yy00ZTFjLTkzOTYtNTEzOGU2OTY3YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzMDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YzMxYjhmMTI4ZjdlZDMzZWRmZTEwMGQzMjVhNmY3YWU5ZWI5MTY0ZWExZGQ4Y2NjMzk4ZGM3NGU3OGVkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1xBzS1gQGGtoleTz9fcEVD4WZBXlpAV-EFJREMyWeAE)

<img width="1718" alt="Snipaste_2023-12-14_11-11-24" src="https://github.com/Ligo04/TwinTex/assets/43836638/1824273f-d68e-4897-9de6-13e1588774e3">

哎，我可以检测到啊，试试放到houdini安装目录的DSO中？

**Comment by nangongliufeng** [comment]
> > 我编译了houdini自带的源码，能搜到，但是twintex搜不到 ![图片](https://private-user-images.githubusercontent.com/87115602/290063089-7df0aeb5-919c-4e1c-9396-5138e6967b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjM2MDcsIm5iZiI6MTcwMjUyMzMwNywicGF0aCI6Ii84NzExNTYwMi8yOTAwNjMwODktN2RmMGFlYjUtOTE5Yy00ZTFjLTkzOTYtNTEzOGU2OTY3YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzMDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YzMxYjhmMTI4ZjdlZDMzZWRmZTEwMGQzMjVhNmY3YWU5ZWI5MTY0ZWExZGQ4Y2NjMzk4ZGM3NGU3OGVkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1xBzS1gQGGtoleTz9fcEVD4WZBXlpAV-EFJREMyWeAE)
> 
> <img alt="Snipaste_2023-12-14_11-11-24" width="1718" src="https://private-user-images.githubusercontent.com/43836638/290389291-1824273f-d68e-4897-9de6-13e1588774e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjQ0MjksIm5iZiI6MTcwMjUyNDEyOSwicGF0aCI6Ii80MzgzNjYzOC8yOTAzODkyOTEtMTgyNDI3M2YtZDY4ZS00ODk3LTlkZTYtMTNlMTU4ODc3NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzMjIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZTk5ZWY3NzI2MmY0MTQ4YTBkMDkzNjRkYmRmZThmMzk5ZTY3OWQ4YjlmYmE1ZWY3NjM2MzYxZGZhMDRmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._46btk5sijRH3q0y8METLMrIvG4sUDmzqAIQD1ur97E">
> 
> 哎，我可以检测到啊，试试放到houdini安装目录的DSO中？

好的，我昨天好像试过了，我再试一下

**Comment by nangongliufeng** [comment]
> > > 我编译了houdini自带的源码，能搜到，但是twintex搜不到 ![图片](https://private-user-images.githubusercontent.com/87115602/290063089-7df0aeb5-919c-4e1c-9396-5138e6967b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjM2MDcsIm5iZiI6MTcwMjUyMzMwNywicGF0aCI6Ii84NzExNTYwMi8yOTAwNjMwODktN2RmMGFlYjUtOTE5Yy00ZTFjLTkzOTYtNTEzOGU2OTY3YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzMDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YzMxYjhmMTI4ZjdlZDMzZWRmZTEwMGQzMjVhNmY3YWU5ZWI5MTY0ZWExZGQ4Y2NjMzk4ZGM3NGU3OGVkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1xBzS1gQGGtoleTz9fcEVD4WZBXlpAV-EFJREMyWeAE)
> > 
> > 
> > <img alt="Snipaste_2023-12-14_11-11-24" width="1718" src="https://private-user-images.githubusercontent.com/43836638/290389291-1824273f-d68e-4897-9de6-13e1588774e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjQ0MjksIm5iZiI6MTcwMjUyNDEyOSwicGF0aCI6Ii80MzgzNjYzOC8yOTAzODkyOTEtMTgyNDI3M2YtZDY4ZS00ODk3LTlkZTYtMTNlMTU4ODc3NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzMjIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZTk5ZWY3NzI2MmY0MTQ4YTBkMDkzNjRkYmRmZThmMzk5ZTY3OWQ4YjlmYmE1ZWY3NjM2MzYxZGZhMDRmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._46btk5sijRH3q0y8METLMrIvG4sUDmzqAIQD1ur97E">
> > 哎，我可以检测到啊，试试放到houdini安装目录的DSO中？
> 
> 好的，我昨天好像试过了，我再试一下

不知道为什么还是搜不到

**Comment by kuaiqushangzixiba** [comment]
因为只有用指定版本才可以，我也是搜不到一开始，替换指定版本后可以搜到

**Comment by kuaiqushangzixiba** [comment]
在19.5.403上可行。但我没有看懂作者的数据集是如何调整的，如果你成功了可以告知我一下。

**Comment by nangongliufeng** [comment]
> 在19.5.403上可行。但我没有看懂作者的数据集是如何调整的，如果你成功了可以告知我一下。
已经放弃了
